Replace cmake with cc
purpleprotocol/mimalloc_rust pull request #58
Opened 2021-02-12 10:43 UTC by Jake-Shadle

This PR replaces the usage of cmake with just straight usage of cc. It replicates some of the logic in the cmakelists but is simplified since this crate only builds a static lib.

Resolves: #51

2021-02-12 12:15 UTC, maroider commented on README.md
> +```ini
```suggestion
```toml
```

2021-02-12 12:46 UTC, Jake-Shadle commented on README.md
> +```ini
This was actually intentional, some markdown renderers don't actually handle the `toml` code fence, whereas `ini` is usually recognized and tends to be highlighted correctly, at least for simpler code blocks such as this, but I can of course change it to be toml.

2021-02-12 12:52 UTC, maroider commented on README.md
> +```ini
Huh, TIL. I have no stake in this either way. It just struck me as odd.

2021-02-21 13:35 UTC, repi commented
Possible to get this merged in and publish a new release? Thanks!

2021-03-04 21:22 UTC, repi commented
@octavonce any thoughts on getting this in? think it would be beneficial to most and we would be really happy getting rid of our fork

2021-03-04 23:03 UTC, thomcc requested changes
So, I was working on this at one point and got too busy to continue (and forgot), so I'm thrilled to see it picked up. The version I had was more complex since it kept the `cmake` support under a flag, but I think this is better.

That said, there are a few nits I have.

The most important one is probably mimicing MI_BUILD_OBJECT rather than MI_BUILD_STATIC, since it has many upsides and basically no downsides compared to what we're doing here.

2021-03-04 23:03 UTC, thomcc commented on libmimalloc-sys/build.rs
> +    build.define("MI_DEBUG", "0");
We should eventually have an option to turn this on. That said, we should set `build.define("NDEBUG", None)` here too if we're doing this. Note that `cmake` will do this automatically, but `cc` does not.

2021-03-04 23:03 UTC, thomcc commented on libmimalloc-sys/build.rs
> +        if target_os != "windows" {
This should check the target family, not target_os

2021-03-04 23:43 UTC, thomcc commented on libmimalloc-sys/build.rs
>      if cfg!(feature = "override") {
(Actually, probably best to address that separately)

2021-03-04 23:43 UTC, thomcc commented on libmimalloc-sys/build.rs
> +    build.define("MI_DEBUG", "0");
Hmm, while mimalloc does use NDEBUG, it's not for assertions and just for a couple extra things. I'll file an issue with mimalloc, what we have here is fine actually.

2021-03-04 23:48 UTC, thomcc commented
Here's a (tested) patch containing all my suggestions: https://gist.github.com/thomcc/3a499f95c68ad8c8698f61235b1a0fa5

2021-03-06 14:20 UTC, merged