Add no_std to libmimalloc-sys lib.rs & use libc for platform deps
purpleprotocol/mimalloc_rust pull request #61
Opened 2021-02-28 17:39 UTC by asrael

Fixes #59

2021-03-04 23:18 UTC, thomcc requested changes
As-is this is more or less completely wrong, sadly.

2021-03-04 23:18 UTC, thomcc commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
`.cargo/config` is workspace-local, it doesn't apply outside this repo (e.g. it won't apply for code that depends on this crate via crates.io). Also, what you have is only linux, which is not the only OS.

The right way to do this *would* be to add something like this into libmimalloc-sys/src/lib.rs, but it's actually wrong too:

```rust
// (don't actually do this)
#[link(name = "c")]
extern {}
```

Unfortunately, different OSes call the c library different things. In general, getting this right is a bit tricky.

```toml
# in the -sys crate
[features]
# ...
default = ["libc"]

[dependencies]
# note: default-features=false prevents linking against `libc`
libc = { version = "0.2", default-features = false, optional = true }
```

And then `#[cfg(feature = "libc")] extern crate libc;` inside the lib.rs of the -sys crate to force it to be linked. The assumption is then that if anybody who disables this feature is responsible for figuring out how to link to the platform libc themselves.

You don't need this on windows for mimalloc for various reasons (it builds as C++ and so cmake/cc will handle linking the CRT in properly), so this could be `[target.'cfg(unix)'.dependencies]` but it doesnt actually matter

2021-03-04 23:39 UTC, Systemcluster commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
The `.cargo/config` here is just for instructing the test cases to link a libc, nothing more.

In this form the duty of linking one lies with the end-user, yes. If they use `std`, which was mandatory until now, nothing changes and a libc is linked by default. Otherwise they have to do so themselves.

I don't think it's the libraries responsibility to link a libc, but it's something for the final application to decide, no?

2021-03-05 00:37 UTC, thomcc commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
> I don't think it's the libraries responsibility to link a libc, but it's something for the final application to decide, no?

Unfortunately the order flags are passed to the linker means that dependencies are responsible for this. Sometimes it will work otherwise, but in general it's more of a "happens to work" than a guarantee.

2021-03-06 18:28 UTC, asrael commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
I agree, I was sort of just bashing around on this branch to get it to work. In my own projects I normally just link libc using a build.rs script. Would that work better here instead of the cargo config?

2021-03-06 18:38 UTC, thomcc commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
I think we should just link the `libc` crate.

The alternative is to duplicate something like this logic to get the right `rt`, `dl`, `c`, and `pthread` libs (which are the libraries mimalloc depends on):

https://github.com/rust-lang/libc/blob/d4080d15c55366b531ebbf799267d8c00580a892/src/unix/mod.rs#L300-L386

E.g. despite the fact that it seems like it should be trivial, it isn't :(

2021-03-06 18:40 UTC, thomcc commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
I also think we should only do this conditionally, but unfortunately, dubious choices about default features (#39) mean that everybody sets `default-features=false`, and so it's a bit tricker since the normal "put it behind an on-by-default feature" approach doesn't really work :(

2021-03-06 19:36 UTC, asrael commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
When I linked the libc crate in both the test crate and the sys crate it failed CI on the AMD 64 Xenial builds for missing a libc symbol atexit, wasn't sure if that's then maybe a libc crate issue.

2021-03-06 23:48 UTC, thomcc commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
The `libmimalloc-sys/sys-test` is for verifying type signatures, not runtime validation, so the kinds of errors its likely to get here are way different. I don't actually think it's likely to be related to your issue.

Can you elaborate more about how things failed though?

2021-03-07 01:18 UTC, asrael commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
```c
libmimalloc-secure-debug.a(init.c.o): in function `mi_process_load': 
mimalloc_rust/libmimalloc-sys/c_src/mimalloc/src/init.c:447: undefined reference to `atexit'
```

If I remove the .cargo/config, I receive this error during CI from the Linux builds.

2021-03-07 01:32 UTC, asrael commented on .cargo/config
> +rustflags = ["-C", "link-args=-lc"]
Okay, well I was receiving that error prior to the cmake-rs -> cc-rs switch over. So really it's good to go with just this tiny change I hope? :)

2021-05-14 13:04 UTC, asrael commented
This is probably stale at this point, I haven't kept up with mimalloc and am instead using a different allocator.

2021-05-14 13:04 UTC, closed without merging